---
apiVersion: v1
kind: Service
metadata:
  name: christelmusic-nl
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: christelmusic-nl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: christelmusic-nl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: christelmusic-nl
  template:
    metadata:
      labels:
        app: christelmusic-nl
    spec:
      containers:
        - name: christelmusic-nl-nginx
          image: daanvm/christelmusic.nl-nginx:latest
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                # Gracefully shutdown nginx
                command: ["/bin/bash", "-c", "/bin/sleep5 && /usr/sbin/nginx -s quit"]

---
apiVersion: v1
kind: Service
metadata:
  name: christelmusic-nl-php
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: christelmusic-nl-php
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: christelmusic-nl-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: christelmusic-nl-php
  template:
    metadata:
      labels:
        app: christelmusic-nl-php
    spec:
      containers:
        - name: christelmusic-nl-php
          image: daanvm/christelmusic.nl-php:latest
          env:
            - name: IFTTT_KEY
              valueFrom:
                secretKeyRef:
                  name: ifttt
                  key: key
          ports:
            - containerPort: 9000
