---
apiVersion: v1
kind: Service
metadata:
  name: daanvm-nl
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: daanvm-nl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daanvm-nl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daanvm-nl
  template:
    metadata:
      labels:
        app: daanvm-nl
    spec:
      containers:
        - name: daanvm-nl-nginx
          image: daanvm/daanvm.nl-nginx:latest
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                # Gracefully shutdown nginx
                command: ["/bin/bash", "-c", "/bin/sleep5 && /usr/sbin/nginx -s quit"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daanvm-nl-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daanvm-nl-php
  template:
    metadata:
      labels:
        app: daanvm-nl-php
    spec:
      containers:
        - name: daanvm-nl-php
          image: daanvm/daanvm.nl-php:latest
          ports:
            - containerPort: 9000
